[boot]
systemd = true
command = "service udev start; modprobe vhci-hcd"

# usbipd.exe bind -i 2341:805a
# usbipd.exe wsl attach -i 2341:805a [-d DISTRO] [-a]
# usbipd.exe list

# sudo modprobe vhci-hcd cp210x
# cat /sys/devices/platform/vhci_hcd.0/status
# lsusb -d 2341:805a [-v]
